# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c063e4c1db909ec92fcb1e320945083fd7d1d14589a992171660ff7d6fef9f63c0f4e34ea4e749e7b5bec8e6b51bf70d1013ee942ade725ec01a7129402fd7ca
  amazon_access_key_id: AKIAIR2LG77QWJO3SD5A
  amazon_secret_access_key: 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
  stripe_pulbic_key: pk_test_A4TfZpSkQjUEgRkTPtgndwwp %>
  stripe_secret_key: sk_test_qHk7kvBbpjFFTDbnK545gKlW %>
test:
  secret_key_base: dc96442feff1348eec93db8d54c4bd32f7b4709d894854114bc6b583b885e04b86379ea570e8aa944af4f92f4c727530de377f5d524938b83457da08931ca4a3
  amazon_access_key_id: AKIAIR2LG77QWJO3SD5A
  amazon_secret_access_key: 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
  stripe_pulbic_key: pk_test_A4TfZpSkQjUEgRkTPtgndwwp %>
  stripe_secret_key: sk_test_qHk7kvBbpjFFTDbnK545gKlW %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  amazon_access_key_id: AKIAIR2LG77QWJO3SD5A
  amazon_secret_access_key: 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
  stripe_pulbic_key: <%= ENV['PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['SECRET_KEY'] %>

